[package]
name = "sttd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.199", features = ["derive"] }
serde_json = "1.0.116"
clap = { version="4.0", features = ["derive"]}
